[Week8] DongLee99
Learning-Now/springboot-study-orm-jpa pull request #26
Opened 2021-08-31 12:39 UTC by DongLee99

2021-09-05 07:52 UTC, PandaHun requested changes

2021-09-05 07:52 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Numbers.java
> +                                .map(stringNumber -> new Number(stringNumber))
```suggestion
                                .map(Number::new)
```

2021-09-05 07:52 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Number.java
> +    public Number(String stringNumber) {
`stringNumber`라는 매개변수명이 더 나은 매개변수명을 가질 순 없을까요

2021-09-05 07:52 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Numbers.java
> +    public Numbers(String [] stringNumbers) {
`stringNumbers`라는 매개변수명이 더 나은 매개변수명을 가질 순 없을까요

2021-09-05 07:52 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Numbers.java
> +}
메서드의 선언순서를 지켜주세요
`override`된 메서드들이 더 아래에 나올 수 있도록

2021-09-05 07:52 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Numbers.java
> +        return (int) numbers.stream()
```suggestion
        return numbers.size();
```
로 충분하지 않나요?

2021-09-05 07:52 UTC, PandaHun commented on practice/tdd/src/main/java/service/StringCalculator.java
> +        if (input.isEmpty()){
"     " 이 입력된다면? 
`isEmpty()`의 원형을 한번 확인해보세요

2021-09-05 07:52 UTC, PandaHun commented on practice/tdd/src/main/java/service/StringCalculator.java
> +                                .sum();
위의 코드를 확인하면 `delimiter`가 왜 `sum()`을 하지라고 생각하거나, 혹은 `split()`의 결과가 무엇인지 확인해야 하는 불편한 코드입니다.

해당 코드를 조금 더 이해하기 쉽게 변형해보세요

2021-09-10 13:21 UTC, PandaHun requested changes
포맷팅 맞춰주세요

2021-09-10 13:21 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Delimiter.java
> +        return Objects.hash(value);
👍

2021-09-10 13:21 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Number.java
> +    private static boolean isNumber(String number) {
위 3 메서드는 왜 `static` 메서드 인가요?

2021-09-10 13:21 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Number.java
> +    private static final String NUMBER_ERROR_MESSAGE = "Error : 숫자가 아닌값이 입력되었습니다.";
두 변수 모두 네이밍이 충분한 의미를 갖고 있지 못한 것 같아요

2021-09-10 13:21 UTC, PandaHun commented on practice/tdd/src/main/java/service/StringCalculator.java
> +        Pattern pattern = Pattern.compile(CUSTOM_PATTERN);
만약에 패턴을 설정하는 방법이 추가된다면?
`Pattern` 객체를 더 늘릴건가요?

2021-09-10 13:21 UTC, PandaHun commented on practice/tdd/src/main/java/service/StringCalculator.java
> +        if (checkCustom(input)) {
체크를 두 번 하는 번거로움이 발생하는 것 같은데 한 번만 할 순 없을까요?
- 지금 한번
- `Delimiter`객체 생성때 한번

2021-09-10 13:21 UTC, PandaHun commented on practice/tdd/src/test/java/domain/DelimiterTest.java
> +    void createDelimiter() {
Custom 구분자는요?

2021-09-10 13:21 UTC, PandaHun commented on practice/tdd/src/test/java/domain/NumbersTest.java
> +    void createNumber(List<Number> values) {
exception Test 아닌가요?

2021-09-10 13:21 UTC, PandaHun commented on practice/tdd/src/test/java/service/StringCalculatorTest.java
> +        String input = "";
공백의 칸수를 늘려보죠?

2021-09-13 01:55 UTC, DongLee99 commented on practice/tdd/src/main/java/domain/Number.java
> +    private static boolean isNumber(String number) {
재귀를 통한 생성자를 만들어주면서 아직 생성자가 실행되지 않아 객체가 생성되지 않아서 그에 따른 메소드 또한 사용이 불가능 하여 static으로 선언 해주었는데 지금 생각해보니까 Util로 빼는게 좀더 맞는 방법인지 궁금합니다.

2021-09-13 03:19 UTC, DongLee99 commented on practice/tdd/src/main/java/service/StringCalculator.java
> +        if (checkCustom(input)) {
변경 후 delimiter가 커스텀인지 디폴트인지 체크 하는 부분을 생성자 부분에 넣어보니 체크에서 set까지 수행하여 역할을 넘어서는 행위를 하는것 처럼 느껴지는데 이를 해결할 방안이 있을까요?

2021-09-13 04:01 UTC, DongLee99 commented on practice/tdd/src/test/java/service/StringCalculatorTest.java
> +        String input = "";
공백의 칸수를 늘렸을때 숫자 외의 값이 입력되었다는 exception이 터집니다.

2021-09-16 22:52 UTC, PandaHun approved these changes

2021-09-16 22:52 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Number.java
> +    private static boolean isNumber(String number) {
`재귀를 통한 생성자를 만들어주면서 아직 생성자가 실행되지 않아 `라는 말이 이해가 잘 가지 않네요
`static` 메서드가 아니여도 충분히 가능할 것으로 보입니다.
강하게 얘기하면 `static`은 객체지향적이지 않다고 생각합니다.

2021-09-16 22:52 UTC, PandaHun commented on practice/tdd/src/main/java/domain/Number.java
> +            throw new RuntimeException(RUNTIME_ERROR_MESSAGE);
변수명이 충분한 의미를 갖고 있을까요?

2021-09-16 22:52 UTC, PandaHun commented on practice/tdd/src/main/java/service/StringCalculator.java
> +        if (checkCustom(input)) {
추상화를 생각해보면 어떨까요?
코드에 의존하기 보단 행동에 의존하는 객체라면 괜찮을 것 같은데요?

2021-09-22 12:57 UTC, closed without merging