[Week8] jeongyuneo
Learning-Now/springboot-study-orm-jpa pull request #27
Opened 2021-09-04 02:53 UTC by jeongyuneo

2021-09-05 08:10 UTC, PandaHun requested changes

2021-09-05 08:10 UTC, PandaHun commented on week7-tdd/src/main/java/week7/NewTddCalculator.java
> +        if (data.isEmpty()) {
"     " 이 입력된다면?
isEmpty()의 원형을 한번 확인해보세요

2021-09-05 08:10 UTC, PandaHun commented on week7-tdd/src/main/java/week7/domain/Number.java
> +    private int validate(String value) {
검증도 변환도 수행하는 두 책임을 갖고 있는 메서드네요?

2021-09-05 08:10 UTC, PandaHun commented on week7-tdd/src/main/java/week7/serivce/DelimiterExtractor.java
> +        return delimiter + OR_OPERATOR + data.substring(data.indexOf(FIRST_SEPARATOR)+2, data.indexOf(LAST_SEPARATOR));
`+2`가 의미하는게 뭐죠?

2021-09-05 08:10 UTC, PandaHun commented on week7-tdd/src/main/java/week7/serivce/DelimiterExtractor.java
> +        return delimiter + OR_OPERATOR + data.substring(data.indexOf(FIRST_SEPARATOR)+2, data.indexOf(LAST_SEPARATOR));
그리고 문자열 연산과 같은경우는 이펙티브 자바 아티클을 참조하면 좋을 듯 합니다.
https://www.corejavaguru.com/effective-java/items/51

2021-09-05 08:10 UTC, PandaHun commented on week7-tdd/src/main/java/week7/domain/Delimiter.java
> +    public void customize(String customizedDelimiter) {
추상화를 사용한다면 객체의 불변성이 깨지는 일을 없앨 수 있을 것같은데?

2021-09-06 14:12 UTC, jeongyuneo commented on week7-tdd/src/main/java/week7/domain/Number.java
> +    private int validate(String value) {
수정 완료

2021-09-06 14:30 UTC, jeongyuneo commented on week7-tdd/src/main/java/week7/NewTddCalculator.java
> +        if (data.isEmpty()) {
요구사항 예시에서 아무것도 입력하지 않을 시에만 0을 반환했기 때문에 공백 문자 입력 시에는 숫자 이외의 값으로 처리해서 예외를 발생시켰습니다.

2021-09-11 00:41 UTC, jeongyuneo commented on week7-tdd/src/main/java/week7/serivce/DelimiterExtractor.java
> +        return delimiter + OR_OPERATOR + data.substring(data.indexOf(FIRST_SEPARATOR)+2, data.indexOf(LAST_SEPARATOR));
수정 완료

2021-09-11 02:54 UTC, jeongyuneo commented on week7-tdd/src/main/java/week7/domain/Delimiter.java
> +    public void customize(String customizedDelimiter) {
수정 완료

2021-09-13 01:26 UTC, PandaHun requested changes

2021-09-13 01:26 UTC, PandaHun commented on week7-tdd/src/main/java/week7/domain/Delimiter.java
> +public abstract class Delimiter {
추상 클래스를 사용 했을 때의 장점과 단점은?

2021-09-13 01:26 UTC, PandaHun commented on week7-tdd/src/main/java/week7/NewTddCalculator.java
> +    private static final String LAST_SEPARATOR = "\n";
이 값을 알아야 할 필요가 있을지를 생각을 더 해봐야 할 것 같은데요?

2021-09-13 01:26 UTC, PandaHun commented on week7-tdd/src/main/java/week7/NewTddCalculator.java
> +            data = data.substring(data.indexOf(LAST_SEPARATOR)+LAST_SEPARATOR.length());
정제가 되서 후에 `Delimiter`가 추가동작을 하는 느낌이라,
`Delimiter`가 온전한 기능을 못하는 것 같은데 어떻게 생각하시나요?

2021-09-13 01:26 UTC, PandaHun commented on week7-tdd/src/main/java/week7/NewTddCalculator.java
> +                ).collect(Collectors.toList());
포맷

2021-09-13 01:26 UTC, PandaHun commented on week7-tdd/src/main/java/week7/domain/Numbers.java
> +        this.numbers = new ArrayList<>(numbers);
👍

2021-09-13 01:49 UTC, jeongyuneo commented on week7-tdd/src/main/java/week7/NewTddCalculator.java
> +                ).collect(Collectors.toList());
수정 완료

2021-09-13 07:43 UTC, jeongyuneo commented on week7-tdd/src/main/java/week7/NewTddCalculator.java
> +    private static final String LAST_SEPARATOR = "\n";
수정 완료

2021-09-13 13:42 UTC, jeongyuneo commented on week7-tdd/src/main/java/week7/NewTddCalculator.java
> +            data = data.substring(data.indexOf(LAST_SEPARATOR)+LAST_SEPARATOR.length());
수정 완료

2021-09-17 01:57 UTC, jeongyuneo commented on week7-tdd/src/main/java/week7/domain/Delimiter.java
> +public abstract class Delimiter {
추상화의 장점은 상속을 통해 중복 코드를 줄일 수 있고, 자식 클래스를 그룹화할 수 있는 것입니다.
단점으로는 추상 클래스는 자식 클래스에 추상 메소드의 구현을 강제하지 않아 추상 클래스의 자식 클래스도 추상 클래스가 될 수 있어 이런 경우 가독성이 떨어집니다.

2021-09-22 12:50 UTC, PandaHun approved these changes

2021-09-22 12:50 UTC, PandaHun commented on week7-tdd/src/main/java/week7/domain/Delimiter.java
> +public abstract class Delimiter {
질문이랑 답변이 매치 되지 않는것 같아요

추상화가 아니라 추상 클래스의 장단을 묻고 있고,
답변은 추상화의 장점 이라면서 추상 클래스의 장점을 말하고 있어요.

2021-09-22 12:56 UTC, closed without merging

2021-09-25 10:37 UTC, jeongyuneo commented on week7-tdd/src/main/java/week7/domain/Delimiter.java
> +public abstract class Delimiter {
답변할 때 제대로 확인하지 못한 것 같습니다. 수정하겠습니다.