[1week] DongLee99
Learning-Now/springboot-study-orm-jpa pull request #5
Opened 2021-07-16 11:12 UTC by DongLee99

2021-07-17 14:34 UTC, Livenow14 requested changes
Pr 전 전반적으로 코드 체크 확인부탁드랴요

2021-07-17 14:34 UTC, Livenow14 commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +    @GetMapping("/find/{id}")
Url에 행동을 표현한 이유가 있을까요?

2021-07-17 14:34 UTC, Livenow14 commented on week1/week1/src/main/java/com/livenow/week1/controller/dto/MemberUpdateRequestDto.java
> +        this.name = member.getName();
기본 생성자가 없는데, 잘 동작 할까요?

2021-07-17 14:34 UTC, Livenow14 commented on week1/week1/src/main/java/com/livenow/week1/controller/dto/MemberUpdateRequestDto.java
> +
두줄 띄어쓰기는 의도한 부분일까요??

2021-07-17 14:34 UTC, Livenow14 commented on week1/week1/src/main/java/com/livenow/week1/domain/Member.java
> +    @Id()
@Id에 괄호를 명시한 이유가 있을까요??

2021-07-17 14:34 UTC, Livenow14 commented on week1/week1/src/main/java/com/livenow/week1/domain/Member.java
> +        this.age = requestDto.getAge();
도메인이 dto를 의존하고 있네요, 같은 도메인으로 사용할 순 없었을까요?

2021-07-17 14:34 UTC, Livenow14 commented on week1/week1/src/main/java/com/livenow/week1/domain/Team.java
> +<<<<<<< HEAD
HEAD가 포함되어 있네요.
이런부분은 삭제가 좋을거같아요

2021-07-23 23:03 UTC, PandaHun approved these changes
조금 더 생각할 부분을 남겨뒀고
Approve할께

2021-07-23 23:03 UTC, PandaHun commented on week1/docs/HTTP.md
> +웹상에서 클라이언트와 서버간의 요청/ 응답을 주고 받을 수 이쓴ㄴ 프로토콜이다. 클라이언트가 HTTP 프로토콜을 이용해 서버로 요청을 보내면 서버는 이를 매핑해 알맞은 응답을 클라이언트에게 제공한다.
코드도 문서도 올리기 전에 점검은 필수

2021-07-23 23:03 UTC, PandaHun commented on week1/docs/HTTP.md
> +- 전송할때마다 데이터를 Body 말고 URL끝에 ?와 함께 이름과 쌍을 이루어 전송하게 된다.
이름과 쌍을 이루지 않는 방법도 있을텐데?

2021-07-23 23:03 UTC, PandaHun commented on week1/docs/HTTP.md
> +Get 은 Idempotent / Post 는 Non-Idempotent
👍

2021-07-23 23:03 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +        message.setData(memberService.update(id, requestDto));
수정자로 매번 호출하는 게 생성자 혹은 메서드로 객체한테 맡겨서 호출하는 것 중 뭐가 더 Best Practice 일까?

만약 성공에 대한 Response Message를 바꾸는 요구 사항이 주어진다면?

2021-07-23 23:03 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/controller/dto/MemberSaveRequestDto.java
> +@Data
lombok의 `@Data`는 매우 강하고 많은 기능을 갖고 있어
그만큼 불필요할 가능성도 높은데 사용한 이유는?

2021-07-23 23:03 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/controller/responsemessage/Message.java
> +public class Message {
Java Generic에 대해 알아보는게 좋을 거 같아
Object는 모든 자바 객체의 조상 클래스라서 좋은 설계는 아니라고 생각해

2021-07-26 01:10 UTC, DongLee99 commented on week1/docs/HTTP.md
> +웹상에서 클라이언트와 서버간의 요청/ 응답을 주고 받을 수 이쓴ㄴ 프로토콜이다. 클라이언트가 HTTP 프로토콜을 이용해 서버로 요청을 보내면 서버는 이를 매핑해 알맞은 응답을 클라이언트에게 제공한다.
수정 완료

2021-07-26 01:15 UTC, DongLee99 commented on week1/docs/HTTP.md
> +Get 은 Idempotent / Post 는 Non-Idempotent
👍

2021-07-26 01:19 UTC, DongLee99 commented on week1/week1/src/main/java/com/livenow/week1/controller/dto/MemberSaveRequestDto.java
> +@Data
잘 모르는 어노테이션 사용은 지양하겠습니다.

2021-07-30 03:10 UTC, closed without merging