[1주차] jeongyuneo
Learning-Now/springboot-study-orm-jpa pull request #7
Opened 2021-07-16 16:53 UTC by jeongyuneo

2021-07-18 04:40 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/domain/Member.java
> +    @JoinColumn(name = "team_id")
`fetch` 타입을 지정한 건 좋은데, `cascade`와 같은 영속성 전이에 관련한 부분은 더 공부해야할 것 같습니다.

2021-07-18 04:51 UTC, PandaHun requested changes
전반적으로 코드는 괜찮습니다.

다만 기능 및 다른 부분들에 대해서 필요한 부분들이 있어보입니다.

2021-07-18 04:51 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/domain/Member.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
`fetch` 타입 지정 부분은 👍 
`cascade` 부분에 대해서는 더 공부가 필요할 것 같아요

일반적으로 `cascade`은 연관관계의 주인보단 반대쪽에 설정하는 게 맞습니다

2021-07-18 04:51 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/domain/Member.java
> +    }
모든 경우의 수에 맞춰 생성자를 생성 할 때,
만약에 속성의 수가 10개, 20개 등등 추가된다면 어떨까요?

모든 속성의 순서를 외워야 하지 않을까요?
더 좋은 방법이 있을 것 같아요

2021-07-18 04:51 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/service/MemberService.java
> +    private static Long AGE = 1L;
변수명이 안맞는것 같은데요?

2021-07-18 04:51 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/service/MemberService.java
> +    @Transactional
`Transactional`이 맞을까요?

2021-07-18 04:51 UTC, PandaHun commented on week1/week1/src/test/java/com/livenow/week1/domain/MemberRepositoryTest.java
> +}
마지막 줄은 빈줄 삽입을 해주세요

2021-07-18 04:51 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +    @PostMapping("/find/all")
`RestAPI`에서 과연 동작을 보여주는게 맞을까요?

2021-07-18 04:51 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +    public void saveMember(@RequestParam String name, @RequestParam int age) {
정보가 많다면, parameter로 받는게 맞을까요?
`http post` 메서드에 대해 알아보세요

2021-07-18 09:45 UTC, jeongyuneo commented on week1/week1/src/test/java/com/livenow/week1/domain/MemberRepositoryTest.java
> +}
수정 완료

2021-07-18 10:25 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/service/MemberService.java
> +    private static Long AGE = 1L;
수정 완료

2021-07-18 13:52 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/domain/Member.java
> +    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.PERSIST)
수정 완료

2021-07-18 13:54 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/domain/Member.java
> +    }
수정 완료

2021-07-18 14:07 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/service/MemberService.java
> +    @Transactional
수정 완료

2021-07-18 14:46 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +    @PostMapping("/find/all")
수정 완료

2021-07-18 15:51 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +    public void saveMember(@RequestParam String name, @RequestParam int age) {
수정 완료

2021-07-23 23:39 UTC, PandaHun approved these changes
어느 정도 코드의 윤곽이 잡힌것 같아서 approve 할께
다만 test 코드가 더 많았으면 좋을 것 같아

2021-07-23 23:39 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +    @GetMapping("/all")
`all`이라는 path가 필요할까?

2021-07-23 23:39 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +    public MemberSaveResponseDto saveMember(@RequestBody MemberSaveRequestDto memberSaveRequestDto) {
직접 객체를 넘겨주는 것도 좋지만 Spring Framework에는 `ResponseEntity`라는 것도 있어

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/ResponseEntity.html

2021-07-23 23:39 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/controller/TeamController.java
> +        return teamService.addMember(memberAddRequestDto.getTeamId(), memberAddRequestDto.getMemberId());
만약에 전달해야되는 정보가 많다면 어떨까?
이렇게 하나씩 전달하는게 좋을까? 객체를 넘기는게 좋을까 생각해보면 좋을것 같아

2021-07-23 23:39 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/controller/dto/MemberAddRequestDto.java
> +    public MemberAddRequestDto(Team teamEntity, Member memberEntity) {
`Xxx`객체의 인스턴스는 `xxxEntity`보다는 `xxx`가 낫지 않을까?
```suggestion
    public MemberAddRequestDto(Team team, Member member) {
```

2021-07-23 23:39 UTC, PandaHun commented on week1/week1/src/main/java/com/livenow/week1/service/MemberService.java
> +    public MemberSaveResponseDto save(String name, int age) {
저장하는데 있어서 Transactional 함이 보장되지 않아도 될까?

2021-07-24 16:58 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/controller/TeamController.java
> +        return teamService.addMember(memberAddRequestDto.getTeamId(), memberAddRequestDto.getMemberId());
수정 완료

2021-07-24 17:09 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/controller/dto/MemberAddRequestDto.java
> +    public MemberAddRequestDto(Team teamEntity, Member memberEntity) {
수정 완료

2021-07-24 17:16 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +    @GetMapping("/all")
수정 완료

2021-07-31 04:41 UTC, closed without merging

2021-08-03 05:25 UTC, jeongyuneo commented on week1/week1/src/main/java/com/livenow/week1/controller/MemberController.java
> +    public MemberSaveResponseDto saveMember(@RequestBody MemberSaveRequestDto memberSaveRequestDto) {
수정 완료